/* SPDX-License-Identifier: MIT */
/*
 * Copyright (c) 2025 HiSilicon Technologies Co., Ltd. All rights reserved.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 *
 */

#ifndef LSUB_REGS_H
#define LSUB_REGS_H

/* cfg0 */
#define SHP_SLOT_NUM (0x1 * CFG_DWORD_LEN)
#define SHP_SLOT_DATA_OFF(i) ((0x2 + (i) * 0x10) * CFG_DWORD_LEN)
#define SHP_SLOT_LEN(i) ((0x1 + 0xF + (i) * 0x10) * CFG_DWORD_LEN)
#define SHP_SLOT_DATA_CAP_LEN (2 * CFG_DWORD_LEN)
#define SHP_SLOT_DATA_CTRL_LEN (7 * CFG_DWORD_LEN)

#define ERR_RECORD_LEN (0x1E * CFG_DWORD_LEN)
#define ERR_CTL_REG (0x10 * CFG_DWORD_LEN)
#define UNCTB_ERR_STS (0x12 * CFG_DWORD_LEN)
#define UNCTB_ERR_MASK (0x14 * CFG_DWORD_LEN)
#define UNCTB_ERR_SEV (0x16 * CFG_DWORD_LEN)
#define CTB_ERR_STS (0x18 * CFG_DWORD_LEN)
#define CTB_ERR_MASK (0x1A * CFG_DWORD_LEN)
#define CTB_ERR_SEV (0x1C * CFG_DWORD_LEN)

#define ERR_INFO_LEN (0x31 * CFG_DWORD_LEN)
#define ERR_INFO_CTL_REG (0x10 * CFG_DWORD_LEN)
#define ERR_INFO_CSM_POINT (0x12 * CFG_DWORD_LEN)
#define ERR_INFO_PDC_POINT (0x13 * CFG_DWORD_LEN)
#define SPC_DEF_ERR_INFO (0x14 * CFG_DWORD_LEN)
#define VDR_DEF_ERR_INFO (0x30 * CFG_DWORD_LEN)

#define EMQ_LEN (0x1B * CFG_DWORD_LEN)
#define ERR_MSG_QUE_CTL (0x2 * CFG_DWORD_LEN)
#define EMQ_COR_ERR_CTL (0x4 * CFG_DWORD_LEN)
#define EMQ_COR_ERR_STA (0x5 * CFG_DWORD_LEN)
#define EMQ_UNCOR_NF_ERR_CTL (0x6 * CFG_DWORD_LEN)
#define EMQ_UNCOR_NF_ERR_STA (0x7 * CFG_DWORD_LEN)
#define EMQ_UNCOR_F_ERR_CTL (0x8 * CFG_DWORD_LEN)
#define EMQ_UNCOR_F_ERR_STA (0x9 * CFG_DWORD_LEN)
#define COR_ERR_CON_POINT (0x10 * CFG_DWORD_LEN)
#define COR_ERR_PRO_POINT (0x11 * CFG_DWORD_LEN)
#define COR_ERR_INFO (0x13 * CFG_DWORD_LEN)
#define UNCOR_NF_ERR_CON_POINT (0x14 * CFG_DWORD_LEN)
#define UNCOR_NF_ERR_PRO_POINT (0x15 * CFG_DWORD_LEN)
#define UNCOR_NF_ERR_INFO (0x16 * CFG_DWORD_LEN)
#define UNCOR_F_ERR_CON_POINT (0x18 * CFG_DWORD_LEN)
#define UNCOR_F_ERR_PRO_POINT (0x19 * CFG_DWORD_LEN)
#define UNCOR_F_ERR_INFO (0x1A * CFG_DWORD_LEN)

#endif /* LSUB_REGS_H */