/* SPDX-License-Identifier: MIT */
/*
 * Copyright (c) 2025 HiSilicon Technologies Co., Ltd. All rights reserved.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 *
 */

#ifndef LSUB_REGS_H
#define LSUB_REGS_H

/* cfg0 */
#define SHP_SLOT_NUM (0x1 * CFG_DWORD_LEN)
#define SHP_SLOT_DATA_OFF(i) ((0x2 + (i) * 0x10) * CFG_DWORD_LEN)
#define SHP_SLOT_LEN(i) ((0x1 + 0xF + (i) * 0x10) * CFG_DWORD_LEN)
#define SHP_SLOT_DATA_CAP_LEN (2 * CFG_DWORD_LEN)
#define SHP_SLOT_DATA_CTRL_LEN (7 * CFG_DWORD_LEN)

#define ERR_RECORD_LEN (0x1E * CFG_DWORD_LEN)
#define ERR_CTL_REG (0x10 * CFG_DWORD_LEN)
#define UNCTB_ERR_STS (0x12 * CFG_DWORD_LEN)
#define UNCTB_ERR_MASK (0x14 * CFG_DWORD_LEN)
#define UNCTB_ERR_SEV (0x16 * CFG_DWORD_LEN)
#define CTB_ERR_STS (0x18 * CFG_DWORD_LEN)
#define CTB_ERR_MASK (0x1A * CFG_DWORD_LEN)
#define CTB_ERR_SEV (0x1C * CFG_DWORD_LEN)

#endif /* LSUB_REGS_H */